# Generated by Django 2.0.7 on 2018-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180815_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_name',
            field=models.CharField(default='surviva', max_length=40),
            preserve_default=False,
        ),
    ]
