# Generated by Django 2.0.7 on 2018-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_file',
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_case',
            field=models.TextField(blank=True, null=True),
        ),
    ]
