# Generated by Django 2.0.7 on 2018-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20180815_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
