# Generated by Django 2.0.7 on 2018-08-20 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0007_auto_20180820_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
