# Generated by Django 2.0.7 on 2018-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20180820_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
    ]
