# Generated by Django 2.0.7 on 2018-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_remove_problem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
    ]
