# Generated by Django 2.0.7 on 2018-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_auto_20180824_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='source_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
